window.QUESTIONS = [
  { id: "q-e01", subject: "epi", chapterId: "epi-01", type: "single", stem: "流行病学最核心的研究对象是：", options: ["单个疑难病例", "实验室动物", "人群", "一台诊疗设备"], answer: 2, explain: "流行病学看群体中的分布、因素与干预。" },
  { id: "q-e02", subject: "epi", chapterId: "epi-01", type: "single", stem: "研究者主动给一部分人服药、另一部分人安慰剂，这属于：", options: ["现况研究", "病例对照", "队列研究", "实验性研究"], answer: 3, explain: "是否主动分配干预是观察与实验的分界。" },
  { id: "q-e03", subject: "epi", chapterId: "epi-02", type: "single", stem: "强调“一定期间新发病例”的指标是：", options: ["患病率", "发病率", "病死率", "构成比"], answer: 1, explain: "发病率看新发，患病率看现患。" },
  { id: "q-e04", subject: "epi", chapterId: "epi-02", type: "tf", stem: "病程越长，在其他条件相近时患病率通常越高。", options: ["对", "错"], answer: 0, explain: "患病率受发病和病程共同影响。" },
  { id: "q-e05", subject: "epi", chapterId: "epi-02", type: "noun", stem: "三间分布", answer: "疾病在地区、时间、人群三个维度上的分布。", explain: "描述流行病学的基本框架。" },
  { id: "q-e06", subject: "epi", chapterId: "epi-03", type: "tf", stem: "两个变量存在统计学关联，就可以认定因果关系。", options: ["对", "错"], answer: 1, explain: "关联可能来自混杂、偏倚或反向因果。" },
  { id: "q-e07", subject: "epi", chapterId: "epi-04", type: "single", stem: "现况研究最主要的局限是：", options: ["完全不能描述分布", "暴露与结局的时间先后常难判断", "一定比队列更贵", "不能发现任何线索"], answer: 1, explain: "像拍照，难判谁先谁后。" },
  { id: "q-e08", subject: "epi", chapterId: "epi-04", type: "single", stem: "调查目标人群的全部对象，称为：", options: ["系统抽样", "分层抽样", "普查", "整群抽样"], answer: 2, explain: "普查覆盖全部对象。" },
  { id: "q-e09", subject: "epi", chapterId: "epi-05", type: "calc", stem: "四格表：病例暴露20、病例非暴露10、对照暴露15、对照非暴露30。OR约为：", options: ["0.25", "1.0", "4.0", "2.0"], answer: 2, explain: "OR=ad/bc=20×30/(10×15)=4。" },
  { id: "q-e10", subject: "epi", chapterId: "epi-05", type: "single", stem: "OR=0.6 且 95%CI 为 0.4–0.9，较合理的说法是：", options: ["暴露肯定有害", "暴露可能具有保护作用", "完全没有关联", "可以证明因果"], answer: 1, explain: "OR<1且CI不跨1，提示保护性关联，仍不等于因果证明。" },
  { id: "q-e11", subject: "epi", chapterId: "epi-05", type: "single", stem: "病例对照研究的时间方向通常是：", options: ["先暴露再等结局", "先按结局分组再回顾暴露", "同时随机分配干预", "只描述三间分布"], answer: 1, explain: "先病后暴露，核心指标OR。" },
  { id: "q-e12", subject: "epi", chapterId: "epi-06", type: "calc", stem: "暴露组发病率20%，非暴露组10%。RR是：", options: ["0.5", "2.0", "10%", "30%"], answer: 1, explain: "RR=0.20/0.10=2。" },
  { id: "q-e13", subject: "epi", chapterId: "epi-06", type: "calc", stem: "上题的AR是：", options: ["2", "0.5", "10%", "30%"], answer: 2, explain: "AR=20%−10%=10%。" },
  { id: "q-e14", subject: "epi", chapterId: "epi-06", type: "single", stem: "反映“总人群中可归因于某暴露的发病比例”的是：", options: ["RR", "OR", "ARP", "PARP"], answer: 3, explain: "PARP看人群层面，ARP看暴露组内部。" },
  { id: "q-e15", subject: "epi", chapterId: "epi-07", type: "single", stem: "随机化的主要目的是：", options: ["让结果变得随机", "使组间基线更可比", "一定能双盲", "代替对照"], answer: 1, explain: "随机是为了分组公平，控制混杂。" },
  { id: "q-e16", subject: "epi", chapterId: "epi-08", type: "calc", stem: "金标准有病100人中检出90人，无病200人中误报20人。灵敏度是：", options: ["90%", "80%", "81.8%", "10%"], answer: 0, explain: "灵敏度=90/100=90%。" },
  { id: "q-e17", subject: "epi", chapterId: "epi-08", type: "calc", stem: "上题特异度是：", options: ["90%", "10%", "80%", "95%"], answer: 0, explain: "无病200人，误报20人，TN=180，特异度=180/200=90%。" },
  { id: "q-e18", subject: "epi", chapterId: "epi-08", type: "single", stem: "患病率明显下降时，通常变化更大的是：", options: ["灵敏度", "特异度", "阳性预测值", "试验的物理原理"], answer: 2, explain: "预测值受患病率影响大。" },
  { id: "q-e19", subject: "epi", chapterId: "epi-09", type: "single", stem: "传染病流行过程的三环节是：", options: ["一级、二级、三级预防", "传染源、传播途径、易感人群", "率、比、比例", "随机、对照、盲法"], answer: 1, explain: "控制措施也按这三环写。" },
  { id: "q-e20", subject: "epi", chapterId: "epi-11", type: "tf", stem: "系统评价是方法框架，Meta分析是其中可能采用的定量综合工具。", options: ["对", "错"], answer: 0, explain: "二者不是同义词。" },

  { id: "q-s01", subject: "stats", chapterId: "st-01", type: "single", stem: "由样本计算、用来推断总体的量称为：", options: ["参数", "总体", "统计量", "变量类型"], answer: 2, explain: "参数描述总体，统计量来自样本。" },
  { id: "q-s02", subject: "stats", chapterId: "st-02", type: "single", stem: "明显偏态且有极端值的定量资料，描述集中趋势优先用：", options: ["均数", "中位数", "方差", "标准误"], answer: 1, explain: "中位数更稳健。" },
  { id: "q-s03", subject: "stats", chapterId: "st-04", type: "single", stem: "描述样本均数抽样波动大小的是：", options: ["极差", "标准差", "标准误", "众数"], answer: 2, explain: "标准差看个体离散，标准误看统计量波动。" },
  { id: "q-s04", subject: "stats", chapterId: "st-05", type: "tf", stem: "OR的95%CI跨过1，通常仍可坚定结论为“肯定有关联”。", options: ["对", "错"], answer: 1, explain: "跨过1时证据通常不足以拒绝无关联。" },
  { id: "q-s05", subject: "stats", chapterId: "st-06", type: "tf", stem: "P>0.05 等于证明两组完全没有差异。", options: ["对", "错"], answer: 1, explain: "只说明现有证据不足以拒绝H0。" },
  { id: "q-s06", subject: "stats", chapterId: "st-07", type: "single", stem: "同一批患者治疗前后血压比较，优先考虑：", options: ["两独立样本t检验", "配对t检验", "卡方检验", "Logistic回归"], answer: 1, explain: "同一对象前后属于配对。" },
  { id: "q-s07", subject: "stats", chapterId: "st-08", type: "single", stem: "比较两组患者的治愈率，资料为分类，首先想到：", options: ["t检验", "方差分析", "卡方检验", "Pearson相关"], answer: 2, explain: "率的比较常用卡方。" },
  { id: "q-s08", subject: "stats", chapterId: "st-09", type: "single", stem: "四个治疗组比较平均住院日，不宜首先反复做：", options: ["方差分析", "多次两两t检验", "先看变量类型", "看是否近似正态"], answer: 1, explain: "反复t会抬高I类错误。" },
  { id: "q-s09", subject: "stats", chapterId: "st-10", type: "tf", stem: "相关系数很大，就可以直接写成因果关系。", options: ["对", "错"], answer: 1, explain: "相关不等于因果。" },
  { id: "q-s10", subject: "stats", chapterId: "st-11", type: "single", stem: "结局是是否发生术后感染，并要调整多个混杂因素，优先：", options: ["线性回归", "配对t检验", "Logistic回归", "只做均数比较"], answer: 2, explain: "二分类结局用Logistic。" },
  { id: "q-s11", subject: "stats", chapterId: "st-12", type: "single", stem: "考场选择统计方法的第一问通常是：", options: ["作者是谁", "结局是定量还是分类", "P值是否小于0.01", "样本从哪所医院来"], answer: 1, explain: "先看变量类型。" },
  { id: "q-s12", subject: "stats", chapterId: "st-03", type: "noun", stem: "Z分数", answer: "把原始值转换为离均数多少个标准差的标准化值，Z=(X−μ)/σ。", explain: "用于去掉量纲后比较位置。" },

  { id: "q-p01", subject: "ph", chapterId: "ph-01", type: "single", stem: "公共卫生最核心的对象是：", options: ["一台加速器", "单个住院患者", "人群", "一份合同"], answer: 2, explain: "公卫以人群健康为核心。" },
  { id: "q-p02", subject: "ph", chapterId: "ph-03", type: "single", stem: "接种疫苗属于：", options: ["一级预防", "二级预防", "三级预防", "筛查"], answer: 0, explain: "发病前针对危险因素。" },
  { id: "q-p03", subject: "ph", chapterId: "ph-03", type: "single", stem: "对无症状高危人群做乳腺筛查，属于：", options: ["一级预防", "二级预防", "三级预防", "康复治疗"], answer: 1, explain: "筛查是二级预防。" },
  { id: "q-p04", subject: "ph", chapterId: "ph-03", type: "single", stem: "脑卒中后的康复训练主要属于：", options: ["一级预防", "二级预防", "三级预防", "病因预防"], answer: 2, explain: "减少残疾和促进功能恢复。" },
  { id: "q-p05", subject: "ph", chapterId: "ph-06", type: "single", stem: "突发公共卫生事件处置，首先通常应：", options: ["先写总结报告", "核实并评估是否构成事件、启动监测预警", "只做健康宣教", "先采购大型设备"], answer: 1, explain: "先确认、预警，再调查控制。" },
  { id: "q-p06", subject: "ph", chapterId: "ph-07", type: "tf", stem: "健康促进只等于发宣传单。", options: ["对", "错"], answer: 1, explain: "还包括环境、政策和社会支持。" },
  { id: "q-p07", subject: "ph", chapterId: "ph-04", type: "tf", stem: "效率高就等于公平好。", options: ["对", "错"], answer: 1, explain: "效率和公平需要权衡。" },
  { id: "q-p08", subject: "ph", chapterId: "ph-08", type: "short", stem: "写出“设计防控方案”的六步。", answer: "明确人群与问题→描述负担→找危险因素→一级/二/三级预防→资源与组织→监测评价。", explain: "综合题骨架。" },
  { id: "q-p09", subject: "ph", chapterId: "ph-05", type: "noun", stem: "健康公平", answer: "不同地区、收入、年龄等人群获得健康机会和卫生服务的公正性。", explain: "政策评价必写的一面。" },
  { id: "q-p10", subject: "ph", chapterId: "ph-02", type: "single", stem: "比较年龄结构差异很大的两个地区死亡水平，更合适的是：", options: ["只报粗死亡率", "用标化率或期望寿命等综合指标", "只报病死率", "只报发病人数"], answer: 1, explain: "粗率受年龄结构干扰。" },

  { id: "q-m01", subject: "mp", chapterId: "mp-01", type: "single", stem: "X射线与γ射线最本质的差别在于：", options: ["一个是粒子一个是波", "产生来源不同", "一个有质量一个没有", "完全不是电磁辐射"], answer: 1, explain: "二者都是光子，来源不同。" },
  { id: "q-m02", subject: "mp", chapterId: "mp-02", type: "single", stem: "吸收剂量的单位是：", options: ["Sv", "Bq", "Gy", "eV"], answer: 2, explain: "Gy=J/kg。" },
  { id: "q-m03", subject: "mp", chapterId: "mp-02", type: "single", stem: "辐射防护中更常用的剂量单位是：", options: ["Gy", "Sv", "kg", "Hz"], answer: 1, explain: "Sv用于当量/有效剂量。" },
  { id: "q-m04", subject: "mp", chapterId: "mp-03", type: "single", stem: "临床参考剂量学中最常作为稳定标准工具的是：", options: ["电离室", "普通数码相机", "体温计", "血压计"], answer: 0, explain: "电离室稳定、可追溯。" },
  { id: "q-m05", subject: "mp", chapterId: "mp-04", type: "noun", stem: "建成区", answer: "高能光子入射后，次级电子逐渐建立电子平衡，表面剂量较低、至dmax才达最大的深度区间。", explain: "深度剂量的核心概念。" },
  { id: "q-m06", subject: "mp", chapterId: "mp-05", type: "single", stem: "电子束适合浅表病变，主要因为：", options: ["完全没有剂量", "有限射程，一定深度后剂量快速下降", "一定比光子能量高", "不需要QA"], answer: 1, explain: "看深度剂量特征，不是“更强”。" },
  { id: "q-m07", subject: "mp", chapterId: "mp-07", type: "single", stem: "IMRT的“调强”指的是：", options: ["把总剂量无限制加大", "调节不同射束/子野的强度分布", "只调节机房空调", "取消危及器官限制"], answer: 1, explain: "调的是空间强度，不是蛮力加量。" },
  { id: "q-m08", subject: "mp", chapterId: "mp-08", type: "single", stem: "IGRT主要解决的问题是：", options: ["如何优化剂量分布", "患者/靶区在哪里", "如何产生X射线", "如何收费"], answer: 1, explain: "图像引导做位置确认和校正。" },
  { id: "q-m09", subject: "mp", chapterId: "mp-07", type: "tf", stem: "IMRT和IGRT是同一个意思。", options: ["对", "错"], answer: 1, explain: "一个管剂量塑形，一个管位置。" },
  { id: "q-m10", subject: "mp", chapterId: "mp-09", type: "tf", stem: "TPS算出来的计划很漂亮，就可以不做验证和QA。", options: ["对", "错"], answer: 1, explain: "计算漂亮不等于实施正确。" },
  { id: "q-m11", subject: "mp", chapterId: "mp-10", type: "noun", stem: "Bragg峰", answer: "带电粒子在射程末端附近能量沉积明显增加的深度剂量特征。", explain: "质子/碳离子的核心物理图像。" },
  { id: "q-m12", subject: "mp", chapterId: "mp-10", type: "tf", stem: "质子治疗在任何情况下都一定优于光子治疗。", options: ["对", "错"], answer: 1, explain: "取决于适应证、射程不确定性和资源。" },
  { id: "q-m13", subject: "mp", chapterId: "mp-11", type: "single", stem: "放疗安全链应同时包括：", options: ["只要机器能开机", "计划正确、机器正确、摆位正确、执行正确", "只看DVH好看", "只看患者签字"], answer: 1, explain: "四环缺一不可。" },
  { id: "q-m14", subject: "mp", chapterId: "mp-12", type: "single", stem: "ALARA的含义更接近：", options: ["剂量越大越好", "在达到目的前提下使不必要照射尽可能低", "完全禁止一切照射", "只保护机器不保护人"], answer: 1, explain: "优化原则。" },
  { id: "q-m15", subject: "mp", chapterId: "mp-13", type: "single", stem: "PET成像直接探测的是：", options: ["正电子本身", "湮灭产生的成对约511 keV光子", "超声波", "可见光"], answer: 1, explain: "符合探测的是光子对。" },
  { id: "q-m16", subject: "mp", chapterId: "mp-13", type: "single", stem: "SPECT相对γ相机，关键增加的是：", options: ["多角度采集和断层重建", "改成超声波", "取消准直器且不再探测光子", "变成外照射治疗"], answer: 0, explain: "SPECT是断层版的单光子成像。" },
  { id: "q-m17", subject: "mp", chapterId: "mp-06", type: "short", stem: "用一句话说明近距离治疗为何强调源的位置。", answer: "剂量随距离变化很明显，源的位置和停留时间会直接改变局部剂量。", explain: "距离效应。" },
  { id: "q-m18", subject: "mp", chapterId: "mp-12", type: "short", stem: "默写操作防护三要素。", answer: "时间尽量短、距离尽量远、屏蔽合理。", explain: "和正当性、ALARA、限值一起记。" },

  { id: "q-pol1", subject: "pol", chapterId: "pol-01", type: "single", stem: "马克思主义哲学认为认识的基础是：", options: ["灵感", "书本", "实践", "传闻"], answer: 2, explain: "实践是认识的基础。" },
  { id: "q-pol2", subject: "pol", chapterId: "pol-02", type: "single", stem: "新时代我国社会主要矛盾是：", options: ["阶级矛盾", "美好生活需要与不平衡不充分发展之间的矛盾", "城乡绝对对立", "只存在于经济领域的供需矛盾"], answer: 1, explain: "准确表述必须记住。" },
  { id: "q-pol3", subject: "pol", chapterId: "pol-02", type: "single", stem: "新发展理念不包括：", options: ["创新", "协调", "封闭", "共享"], answer: 2, explain: "创新、协调、绿色、开放、共享。" },
  { id: "q-pol4", subject: "pol", chapterId: "pol-03", type: "single", stem: "近代中国社会性质是：", options: ["完全的封建社会", "半殖民地半封建社会", "发达资本主义社会", "信息社会"], answer: 1, explain: "史纲起点判断。" },
  { id: "q-pol5", subject: "pol", chapterId: "pol-04", type: "tf", stem: "法治思维只要求服从，不谈权利和程序。", options: ["对", "错"], answer: 1, explain: "法治包含权利义务、程序和权力制约。" },
  { id: "q-pol6", subject: "pol", chapterId: "pol-05", type: "single", stem: "按本计划，9月政治应：", options: ["成为每天最主要科目", "只建立框架，把时间留给353和英语", "完全不看", "直接开始默肖四"], answer: 1, explain: "政治后期提升更快。" },

  { id: "q-en1", subject: "en", chapterId: "en-01", type: "single", stem: "The incidence of a disease refers mainly to:", options: ["all existing cases", "new cases in a period", "only deaths", "only hospital beds"], answer: 1, explain: "incidence = 新发。" },
  { id: "q-en2", subject: "en", chapterId: "en-01", type: "single", stem: "“Prevalence” is closest in meaning to:", options: ["how many new cases appear", "how many cases exist at a time", "how deadly a disease is", "how far a beam travels"], answer: 1, explain: "prevalence = 现患。" },
  { id: "q-en3", subject: "en", chapterId: "en-02", type: "single", stem: "In reading, the first useful move is usually to:", options: ["translate every word", "read the questions and locate", "memorize the author's name", "skip the passage"], answer: 1, explain: "题干定位。" },
  { id: "q-en4", subject: "en", chapterId: "en-02", type: "single", stem: "An option with words like “always / never / completely” is often:", options: ["safer", "too absolute", "always correct", "a main-idea sentence"], answer: 1, explain: "绝对化是常见干扰。" },
  { id: "q-en5", subject: "en", chapterId: "en-01", type: "tf", stem: "背完100个单词但第二天全忘，仍然算有效备考。", options: ["对", "错"], answer: 1, explain: "必须进句子复现，并且不断档。" },
  { id: "q-en6", subject: "en", chapterId: "en-01", type: "single", stem: "“Bias” in epidemiology is closest to:", options: ["偏倚", "剂量", "靶区", "屏蔽"], answer: 0, explain: "bias = 偏倚。" },
  { id: "q-en7", subject: "en", chapterId: "en-01", type: "single", stem: "A cohort study usually follows people from:", options: ["outcome back to exposure", "exposure forward to outcome", "only one hospital bill", "a single CT slice"], answer: 1, explain: "队列从暴露跟到结局。" },
  { id: "q-en8", subject: "en", chapterId: "en-02", type: "single", stem: "Main-idea questions are best answered from:", options: ["one rare example only", "opening, ending and topic sentences", "your extra medical knowledge"], answer: 1, explain: "主旨看结构，不靠背景知识。" },
  { id: "q-en9", subject: "en", chapterId: "en-01", type: "single", stem: "“Surveillance” most nearly means:", options: ["一次体检", "持续监测", "只做手术"], answer: 1, explain: "surveillance = 监测。" },
  { id: "q-en10", subject: "en", chapterId: "en-01", type: "single", stem: "ALARA is a principle of:", options: ["radiation protection", "English grammar only", "hospital food"], answer: 0, explain: "防护优化原则。" },
  { id: "q-en11", subject: "en", chapterId: "en-02", type: "tf", stem: "细节题可以只凭印象选，不必回到原文。", options: ["对", "错"], answer: 1, explain: "必须能指回原文一句。" },
  { id: "q-en12", subject: "en", chapterId: "en-01", type: "single", stem: "Relative risk compares:", options: ["two incidence rates", "two hospital names", "two fonts"], answer: 0, explain: "RR比较两组发病率。" },

  { id: "q-pol7", subject: "pol", chapterId: "pol-01", type: "single", stem: "唯物辩证法认为事物发展的根本规律是：", options: ["能量守恒", "对立统一", "供需平衡", "随机抽样"], answer: 1, explain: "对立统一即矛盾规律。" },
  { id: "q-pol8", subject: "pol", chapterId: "pol-01", type: "tf", stem: "意识对物质没有任何能动作用。", options: ["对", "错"], answer: 1, explain: "物质决定意识，意识有能动作用。" },
  { id: "q-pol9", subject: "pol", chapterId: "pol-02", type: "single", stem: "改革开放被定位为：", options: ["可有可无的试验", "决定当代中国命运的关键一招", "只与外贸有关", "只属于史纲年表"], answer: 1, explain: "阶段定位要记准。" },
  { id: "q-pol10", subject: "pol", chapterId: "pol-03", type: "single", stem: "近代中国两大历史任务之一是：", options: ["普及直线加速器", "民族独立和人民解放", "取消一切公共卫生"], answer: 1, explain: "另一项是国家富强和人民富裕。" },
  { id: "q-pol11", subject: "pol", chapterId: "pol-04", type: "single", stem: "法治思维强调的不包括：", options: ["程序", "权利义务", "权力制约", "只讲服从不问依据"], answer: 3, explain: "法治不是单纯听话。" },
  { id: "q-pol12", subject: "pol", chapterId: "pol-05", type: "tf", stem: "因为焦虑，9月就应把政治当成每天第一科目。", options: ["对", "错"], answer: 1, explain: "当前第一是353，第二是英语。" },
];

window.ENGLISH_WORDS = [
  ["incidence", "发病率；发生", "The incidence of the disease rose last year."],
  ["prevalence", "患病率；流行程度", "Prevalence depends on both incidence and duration."],
  ["mortality", "死亡率", "Mortality declined after the new policy."],
  ["morbidity", "发病率/患病情况", "The report compared morbidity across cities."],
  ["exposure", "暴露", "They compared exposure history between groups."],
  ["outcome", "结局", "The primary outcome was 30-day survival."],
  ["cohort", "队列", "The cohort was followed for ten years."],
  ["bias", "偏倚", "Selection bias can distort the association."],
  ["confounder", "混杂因素", "Age may be a confounder in this study."],
  ["randomize", "随机化", "Patients were randomized to two arms."],
  ["placebo", "安慰剂", "The control group received a placebo."],
  ["blind", "盲法的", "The trial was double-blind."],
  ["sensitivity", "灵敏度", "High sensitivity means fewer missed cases."],
  ["specificity", "特异度", "High specificity means fewer false positives."],
  ["screening", "筛查", "Screening aims to find disease earlier."],
  ["prevention", "预防", "Primary prevention happens before disease starts."],
  ["outbreak", "暴发", "An outbreak investigation started immediately."],
  ["surveillance", "监测", "Surveillance data triggered the warning."],
  ["intervention", "干预", "The intervention reduced smoking rates."],
  ["evidence", "证据", "Decisions should be based on the best evidence."],
  ["estimate", "估计", "The study estimated the relative risk."],
  ["significant", "显著的", "The difference was statistically significant."],
  ["interval", "区间", "The 95% confidence interval excluded one."],
  ["variable", "变量", "Outcome variables must be defined first."],
  ["sample", "样本", "A larger sample often gives a narrower interval."],
  ["population", "总体；人群", "Findings should be generalized to the target population carefully."],
  ["dose", "剂量", "The prescribed dose was 60 Gy."],
  ["beam", "射束", "The treatment used several beams."],
  ["target", "靶区", "The high-dose region should cover the target."],
  ["organ", "器官", "Organs at risk need dose constraints."],
  ["image", "影像；成像", "Image guidance confirmed the position."],
  ["accuracy", "准确性", "Setup accuracy affects dose delivery."],
  ["shield", "屏蔽", "Shielding reduces unnecessary exposure."],
  ["radiation", "辐射", "Radiation protection follows ALARA."],
  ["proton", "质子", "Proton therapy uses the Bragg peak."],
  ["isotope", "同位素", "The tracer is a radioactive isotope."],
  ["detect", "探测；发现", "PET detects pairs of photons."],
  ["calibrate", "校准", "The chamber must be calibrated."],
  ["quality", "质量", "Quality assurance is done every day."],
  ["deliver", "实施；给予", "The machine delivered the planned dose."],
  ["associate", "关联", "Smoking is associated with higher risk."],
  ["causal", "因果的", "Association is not necessarily causal."],
  ["risk", "风险", "Relative risk compares two incidence rates."],
  ["ratio", "比", "Odds ratio is common in case-control studies."],
  ["control", "对照；控制", "A proper control group is essential."],
  ["trial", "试验", "A randomized trial can test an intervention."],
  ["ethics", "伦理", "Human trials require ethics approval."],
  ["policy", "政策", "Health policy should consider equity."],
  ["equity", "公平", "Equity is not the same as equality."],
  ["promote", "促进", "The campaign promotes healthy behavior."],
  ["behavior", "行为", "Behavior change needs a supportive environment."],
  ["burden", "负担", "Disease burden includes death and disability."],
  ["chronic", "慢性的", "Chronic diseases need long-term management."],
  ["acute", "急性的", "Acute exposure may cause different effects."],
  ["therapy", "治疗", "Radiation therapy requires precise planning."],
  ["plan", "计划", "The treatment plan was reviewed by a physicist."],
  ["verify", "验证", "Physicists verify the plan before treatment."],
  ["position", "体位；位置", "Daily imaging checks patient position."],
  ["error", "误差；错误", "A small geometric error can matter in IMRT."],
  ["peak", "峰", "The Bragg peak is a key physical feature."],
];

window.ENGLISH_PASSAGES = [
  {
    id: "pass-1",
    title: "短文1｜发病与患病",
    text: "Incidence counts new cases over a period. Prevalence counts existing cases at a time. A disease that lasts many years can have a high prevalence even if its incidence is not very high.",
    qs: [
      { q: "Incidence mainly counts:", opts: ["new cases", "old hospitals", "only deaths"], a: 0 },
      { q: "A long duration may raise:", opts: ["only beam energy", "prevalence", "the Bragg peak"], a: 1 },
    ],
  },
  {
    id: "pass-2",
    title: "短文2｜相关不是因果",
    text: "Two variables may move together. That association can come from a real cause, from chance, or from a confounder. Researchers therefore ask whether changing the exposure would change the outcome.",
    qs: [
      { q: "Moving together always means cause?", opts: ["Yes", "No"], a: 1 },
      { q: "A third factor that distorts the link is a:", opts: ["confounder", "proton", "placebo only"], a: 0 },
    ],
  },
  {
    id: "pass-3",
    title: "短文3｜筛查",
    text: "A sensitive test finds most people who truly have the disease. A specific test correctly clears most people who do not. Predictive values, however, also depend on how common the disease is in the tested group.",
    qs: [
      { q: "Sensitivity is about people who:", opts: ["are truly diseased", "are machines"], a: 0 },
      { q: "Predictive values also depend on:", opts: ["how common the disease is", "only the hospital name"], a: 0 },
    ],
  },
  {
    id: "pass-4",
    title: "短文4｜IMRT与IGRT",
    text: "IMRT shapes the dose. IGRT checks where the patient and the target are. When the dose falls steeply, a small setup error can miss the target or over-dose a normal organ. That is why the two methods are often used together.",
    qs: [
      { q: "IMRT mainly shapes the:", opts: ["dose", "waiting room"], a: 0 },
      { q: "IGRT mainly checks:", opts: ["price", "position"], a: 1 },
    ],
  },
  {
    id: "pass-5",
    title: "短文5｜质子",
    text: "Protons can deposit much of their energy near the end of their range, forming a Bragg peak. This may spare some normal tissue beyond the target. Still, range uncertainty means proton therapy is not automatically better in every case.",
    qs: [
      { q: "The Bragg peak appears near the:", opts: ["end of the range", "hospital gate"], a: 0 },
      { q: "Proton therapy is always better?", opts: ["Yes", "No"], a: 1 },
    ],
  },
  {
    id: "pass-6",
    title: "短文6｜应急",
    text: "An outbreak response starts with confirmation and case definitions. Investigators then describe time, place and person, test hypotheses, and act on the three links: source, route and susceptible people. Communication must tell the public what to do.",
    qs: [
      { q: "The first step is usually to:", opts: ["confirm the outbreak", "buy a linac"], a: 0 },
      { q: "Control follows:", opts: ["source, route, susceptible people", "only slogans"], a: 0 },
    ],
  },
  {
    id: "pass-7",
    title: "短文7｜随机对照",
    text: "In a randomized trial, researchers assign the intervention. Randomization makes groups more comparable. Blinding can reduce biased measurement. The aim is not to make results random, but to make the comparison fair.",
    qs: [
      { q: "Randomization makes groups more:", opts: ["comparable", "wealthy"], a: 0 },
      { q: "The aim of randomization is to make results random.", opts: ["True", "False"], a: 1 },
    ],
  },
  {
    id: "pass-8",
    title: "短文8｜QA",
    text: "A treatment plan can look perfect on the screen. Quality assurance still asks whether the machine, the geometry and the delivery match the plan. Safe radiotherapy needs a correct plan, a correct machine, a correct setup and a correct delivery.",
    qs: [
      { q: "A pretty plan is enough?", opts: ["Yes", "No"], a: 1 },
      { q: "QA checks whether delivery matches the:", opts: ["plan", "advertisement"], a: 0 },
    ],
  },
];

window.TYPE_LABEL = {
  single: "单选",
  tf: "判断",
  calc: "计算",
  noun: "名词解释",
  short: "简答",
  case: "案例",
  multi: "多选",
};
