const {test,expect}=require('@playwright/test'),fs=require('fs'),path=require('path');
const pack=JSON.parse(fs.readFileSync(path.join(__dirname,'../../product-2028-pilot-build/representative-courses.json'),'utf8'));
async function create(page){await page.goto('/');await page.locator('#name').fill('同名手机验收');await page.locator('#create').click();await expect(page.locator('#wrong')).toBeVisible();}
async function answer(page,q){if(q.type==='single')await page.locator('input[name="pick"]').nth(0).check();else if(q.type==='multi')for(const i of q.answer)await page.locator('input[name="pick"]').nth(i).check();else await page.locator('#answer').fill(q.type==='number'?String(q.answer):'主观题自己的原文：尚未完整说明');await page.locator('#submit').click();await expect(page.locator('#next')).toBeVisible();}
for(const u of pack.units)test('R5 '+u.subject+' full answer text and subjective checklist survives reload',async({page})=>{
 await create(page);await page.locator('[data-unit="'+u.id+'"]').click();await expect(page.locator('.current-stage')).toHaveText('现在：学习');await page.locator('#learned').click();await expect(page.locator('.current-stage')).toHaveText('现在：闭卷');await page.locator('#answer').fill('R5闭卷答案');await page.locator('#recall').click();
 const qs=[...u.basicQuestions,...u.applicationQuestions];
 for(const q of qs){await answer(page,q);await expect(page.locator('.question-stem')).toHaveText(q.stem);if(q.type==='single'){await expect(page.locator('.answer-copy').first()).toContainText(q.options[0]);await expect(page.locator('.answer-copy').nth(1)).toContainText(q.options[q.answer]);}if(q.type==='subjective'){await expect(page.locator('.rubric')).toContainText('不给自动分数');await page.locator('input[name="rubric"]').first().check();await expect(page.locator('#rubric-status')).toContainText('待核对');await expect.poll(()=>page.evaluate(async()=>{const b=await profile.exportBackup();return b.sessions.find(s=>s.id==='unit:'+session.unitId)?.draft||'';})).toContain('selfRubric');await page.reload();await page.getByRole('button',{name:/继续 同名手机验收/}).click();await page.locator('[data-unit="'+u.id+'"]').click();await expect(page.locator('input[name="rubric"]').first()).toBeChecked();await expect(page.locator('.answer-copy').first()).toContainText('主观题自己的原文');}await page.locator('#next').click();}
 await page.locator('#back').click();await page.locator('#wrong').click();await expect(page.locator('#app')).not.toContainText('needs-review');await expect(page.locator('#app')).toContainText('我的答案');const b=await page.evaluate(()=>profile.exportBackup());expect(b.events.some(e=>(e.payload?.selfRubric||e.payload?.reflection?.selfRubric)?.includes(0))).toBe(true);
});
test('R5 same-name restored profiles retain independent answers',async({page},info)=>{
 await create(page);await page.locator('[data-unit="'+pack.units[0].id+'"]').click();await page.locator('#learned').click();await page.locator('#answer').fill('原档案不可覆盖');await page.locator('#recall').click();await page.locator('#back').click();const before=await page.evaluate(()=>profile.exportBackup());const wait=page.waitForEvent('download');await page.locator('#backup').click();const file=info.outputPath('r5-synthetic-backup.json');await(await wait).saveAs(file);await page.locator('#logout').click();await page.locator('#restore').setInputFiles(file);await expect(page.locator('#wrong')).toBeVisible();const copy=await page.evaluate(()=>profile.exportBackup());expect(copy.profileId).not.toBe(before.profileId);expect(copy.profile.restoredFrom).toBe(before.profileId);await page.evaluate(()=>profile.updateSettings({dailyMinutes:15}));const original=await page.evaluate(id=>repository.forProfile(id).exportBackup(),before.profileId);expect(original).toEqual(before);await page.locator('#logout').click();await expect(page.locator('[data-profile]')).toHaveCount(2);await expect(page.locator('#app')).toContainText(before.profileId);await expect(page.locator('#app')).toContainText(copy.profileId);await expect(page.locator('#app')).toContainText('备份恢复档案');
});
test('R5 first empty wrong-list and Chinese recall error are usable',async({page})=>{
 await create(page);await page.locator('#wrong').click();await expect(page.locator('#app')).toContainText('暂时没有');await page.locator('#back').click();await page.locator('[data-unit="'+pack.units[0].id+'"]').click();await page.locator('#learned').click();await page.locator('#recall').click();await expect(page.locator('#message')).toContainText('请先填写自己的闭卷回答');await expect(page.locator('#message')).not.toContainText('hidden recall required');await expect(page.locator('#answer')).toBeVisible();
});
test('R5 phone layout keeps actions separate and next stage near top',async({page})=>{
 await page.setViewportSize({width:390,height:844});await create(page);const rects=await page.locator('.task-actions button').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};}));expect(rects).toHaveLength(4);for(const r of rects){expect(r.height).toBeGreaterThanOrEqual(44);expect(r.x).toBeGreaterThanOrEqual(0);expect(r.x+r.width).toBeLessThanOrEqual(391);}for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i],b=rects[j];expect(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y).toBe(true);}await page.locator('[data-unit="'+pack.units[0].id+'"]').click();await page.locator('#learned').click();expect(await page.locator('.current-stage').evaluate(e=>e.getBoundingClientRect().top)).toBeLessThan(200);
});
