'use strict';
const app=document.getElementById('app'),message=document.getElementById('message'),repository=ProfileRepository.createRepository(indexedDB);let pack,profile,controller,session,busy=false,draftWrite=Promise.resolve(),pendingDraft=null;
const JOURNAL='qh2028_product_pending_v1:';
const journalKey=s=>JOURNAL+profile.id+':'+s.unitId;
function journalWrite(s,text){if(typeof localStorage!=='undefined')localStorage.setItem(journalKey(s),JSON.stringify({revision:s.revision||0,stage:s.stage,text}));}
function journalClear(s){if(typeof localStorage!=='undefined')localStorage.removeItem(journalKey(s));}
async function flushPending(){if(!pendingDraft)return;const p=pendingDraft;const next=await p.controller.draft(p.session,p.text);if(controller===p.controller&&session?.id===p.session.id)session=next;if(pendingDraft===p){pendingDraft=null;try{journalClear(p.session);}catch{message.textContent='答案已保存；临时草稿清理失败，原答案不受影响。';}}}
async function openUnit(id){session=await controller.load(id);pendingDraft=null;if(typeof localStorage!=='undefined'){const raw=localStorage.getItem(journalKey(session));if(raw){const p=JSON.parse(raw);if(p.revision===(session.revision||0)&&p.stage===session.stage){session={...session,draft:p.text};pendingDraft={controller,session,text:p.text};}}}render();}

const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function error(e){const known={'hidden recall required':'请先填写自己的闭卷回答','stage':'学习阶段已变化，请返回任务后继续','No submitted answer':'请先提交答案','Transaction aborted':'保存发生冲突或中断，请重新进入课程核对','Transaction failed':'本机保存失败，请重试'};message.textContent='尚未完成保存或读取：'+(known[e.message]||e.message)+'。原有记录保留；未提交文字请勿清除，可重试。';}
async function act(fn){if(busy)return;busy=true;app.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=true);message.textContent='正在读取或保存，请稍候…';try{await draftWrite;await flushPending();await fn();if(message.textContent==='正在读取或保存，请稍候…')message.textContent='操作完成，记录保存在本机';}catch(e){error(e);}finally{busy=false;app.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=false);}}
function bind(id,fn){document.getElementById(id)?.addEventListener('click',()=>act(fn));}
async function home(){const profiles=await repository.listProfiles();pendingDraft=null;app.innerHTML='<h1>今日上岸作战</h1><p>独立测试构建 R5 · iPhone反馈集中修复 · 非正式课程版</p><p>新档案从零开始；原V59数据不会导入或修改。</p><label>本机档案名称<input id="name" maxlength="40" placeholder="例如：我的2028学习"></label><button class="btn block" id="create">新建本机档案</button>'+profiles.map(p=>'<button class="btn block" data-profile="'+esc(p.id)+'">继续 '+esc(p.settings?.displayName||p.id)+' · '+esc(p.id.slice(0,8))+'</button><p class="profile-meta">'+esc(p.restoredFrom?'备份恢复档案':'新建档案')+' · '+esc(new Date(p.createdAt).toLocaleString())+' · 档案编号 '+esc(p.id)+'</p>').join('')+'<label>恢复备份到新档案<input id="restore" type="file" accept="application/json,.json"></label>';bind('create',async()=>{profile=await repository.createProfile(crypto.randomUUID(),{displayName:document.getElementById('name').value||'新学习档案'});await enter();});app.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>act(async()=>{profile=repository.forProfile(b.dataset.profile);await enter();}));document.getElementById('restore').onchange=e=>act(async()=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024)throw Error('备份超过20MB试验限制');profile=await repository.restoreAsNewProfile(crypto.randomUUID(),JSON.parse(await file.text()));await enter();});}
async function enter(){controller=LearningController.createLearningController(CourseEngine,profile,pack.units);await overview();}
async function overview(){session=null;const b=await profile.exportBackup(),plan=LearningController.planDailyTasks(pack.units,b,{minutes:b.profile.settings.dailyMinutes,mode:b.profile.settings.learningMode});app.innerHTML='<h1>现在只做一项</h1><label>今天可学分钟<input id="minutes" type="number" min="15" max="180" value="'+plan.budget+'"></label><label>今天状态<select id="mode"><option value="normal">正常</option><option value="busy">忙碌</option><option value="trip">出差</option><option value="dinner">饭局后</option></select></label><button class="btn" id="plan">保存时间，重新安排</button><p>'+esc(plan.recovering?'断学后先恢复，今天减量。':'')+esc(plan.note)+'</p><p>今日顺序：'+esc(plan.tasks.map(t=>t.title+'（'+t.allottedMinutes+'分钟学习段）').join(' → ')||'样板初学已完成；等到期再测，不虚构新课程。')+'</p><p>本机试用档案：'+esc(b.profile?.settings?.displayName||profile.id)+' · '+esc(profile.id.slice(0,8))+'</p><details><summary>档案编号与来源</summary><p>'+esc(profile.id)+'</p><p>'+esc(b.profile.restoredFrom?'备份恢复自 '+b.profile.restoredFrom:'独立新建档案')+'</p></details>'+pack.units.map(u=>{const s=b.sessions.find(x=>x.id==='unit:'+u.id),r=b.sessions.find(x=>x.id==='review:'+u.id);return '<section class="card"><h2>'+esc(u.title)+'</h2><p>'+esc(s?.stage==='scheduled'?'已完成本轮，待延迟复习':s?'可断点继续':'尚未学习')+(r?' · 复习到期 '+esc(new Date(r.due).toLocaleString()):'')+'</p><button class="btn block" data-unit="'+esc(u.id)+'">学习 / 继续</button></section>';}).join('')+'<nav class="task-actions" aria-label="档案操作"><button class="btn" id="wrong">查看实际错题和待评分</button><button class="btn" id="backup">导出完整本机备份</button><button class="btn" id="update">检查测试版更新</button><button class="btn" id="logout">退出本机档案</button></nav>';app.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>act(async()=>{await openUnit(b.dataset.unit);}));bind('backup',async()=>{const blob=new Blob([JSON.stringify(await profile.exportBackup(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='qinghua-2028-local-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});bind('logout',async()=>{profile=controller=session=null;await home();});bind('wrong',wrong);bind('update',async()=>{if(!('serviceWorker'in navigator))throw Error('此环境不支持PWA更新');const registration=await navigator.serviceWorker.getRegistration();if(!registration)throw Error('离线程序尚未安装');await registration.update();if(registration.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});registration.waiting.postMessage({type:'ACTIVATE_UPDATE'});}else message.textContent='目前没有等待安装的更新';});document.getElementById('mode').value=b.profile.settings.learningMode||'normal';bind('plan',async()=>{await profile.updateSettings({dailyMinutes:Number(document.getElementById('minutes').value)||90,learningMode:document.getElementById('mode').value||'normal'});await overview();});}
const stateText=state=>({'unassessed':'尚未测评','needs-review':'需要复习','initial-understanding':'已有初步理解，仍需复测','delayed-evidence':'已有多次延迟测试证据'}[state]||'尚未完成本轮测试');
function answerText(q,value){if(value===undefined||value===null)return '尚无答案';if(q.type==='single'||q.type==='multi'){const values=Array.isArray(value)?value:[value];return values.map(i=>Number.isInteger(i)&&q.options?.[i]!==undefined?String.fromCharCode(65+i)+'．'+q.options[i]:'选项记录无法对应，请核对原题').join('；');}if(q.type==='number'){return typeof value==='object'?String(value.value)+' '+(value.unit||''):String(value)+' '+(q.unit||'');}return String(value);}
function answerCard(payload){const q=payload.questionSnapshot;return '<h2 class="question-stem">'+esc(q.stem)+'</h2><p class="answer-copy">我的答案：'+esc(answerText(q,payload.answer))+'</p><p class="answer-copy">'+(q.type==='subjective'?'参考答案（待人工核对）：':'正确答案：')+esc(answerText(q,q.answer))+'</p><p class="answer-copy">对应解析：'+esc(q.explanation)+'</p>';}
function rubricCard(q,checks=[]){if(q.type!=='subjective')return '';return '<section class="rubric"><h3>评分要点与待完善项</h3><p>待核对，不给自动分数。请对照自己的原答案逐项确认；未勾选只表示尚未确认，不代表系统判定遗漏。</p>'+q.rubric.map((point,i)=>'<label class="rubric-item"><input type="checkbox" name="rubric" value="'+i+'" '+(checks.includes(i)?'checked':'')+'> '+esc(point)+'</label>').join('')+'<p id="rubric-status" role="status"></p></section>';}
async function wrong(){message.textContent='正在读取本档案错题…';const b=await profile.exportBackup(),rows=b.events.filter(x=>x.action==='answered'&&x.payload?.grade&&x.payload.grade.correct!==true&&x.payload.questionSnapshot);app.innerHTML='<h1>错题与待评分答案</h1><p>当前档案：'+esc(b.profile.settings.displayName)+' · '+esc(profile.id.slice(0,8))+'</p>'+(!rows.length?'<section class="card"><p>本档案暂时没有已记录的错题或待评分答案。尚未提交的回答不会显示在这里。</p></section>':'')+rows.map(x=>{const reason=b.events.filter(e=>e.unitId===x.unitId&&['feedback-read','scheduled'].includes(e.action)&&(e.payload?.questionId===x.payload.questionId||e.payload?.reflection?.questionId===x.payload.questionId)).at(-1)?.payload;const r=b.sessions.find(e=>e.id==='review:'+x.unitId);const label={concept:'概念没理解',calculation:'计算错误',reading:'审题错误',memory:'没有记住',incomplete:'回答不完整',unclassified:'尚未判断'};const f=reason?.reflection||reason;return '<section class="card">'+answerCard(x.payload)+'<p>'+esc(x.payload.grade.correct===null?'主观题待核对，无自动评分':'本次答错')+'</p>'+((x.payload.questionSnapshot.rubric||[]).map((p,i)=>'<p>评分要点 '+(i+1)+'：'+esc(p)+' · '+(f?.selfRubric?.includes(i)?'已自行确认':'待核对或待补充')+'</p>').join(''))+'<p>自述错因：'+esc(label[f?.cause]||'尚未判断')+' · '+esc(f?.note||'')+'</p><p>该单元最新证据：'+esc(stateText(r?.state))+'；历史原错题保留，单元复习通过不代表原题已复测。</p></section>';}).join('')+'<button class="btn block" id="back">返回任务</button>';bind('back',overview);message.textContent=rows.length?'已读取 '+rows.length+' 条错题与待核对答案':'已读取，本档案暂无错题';}

function wireDraft(){const save=text=>{if(busy)return;pendingDraft={controller,session,text};try{journalWrite(session,text);}catch(e){error(e);}draftWrite=draftWrite.then(()=>flushPending()).catch(error);};const reflection=document.getElementById('reflection'),cause=document.getElementById('cause');if(reflection&&cause){try{const saved=JSON.parse(session.draft||'{}');reflection.value=saved.note||'';cause.value=saved.cause||'unclassified';}catch{}reflection.oninput=cause.onchange=()=>save(JSON.stringify({note:reflection.value,cause:cause.value,selfRubric:[...app.querySelectorAll('input[name="rubric"]:checked')].map(x=>Number(x.value))}));const checks=(()=>{try{return JSON.parse(session.draft||'{}').selfRubric||[];}catch{return [];}})();const rubrics=app.querySelectorAll('input[name="rubric"]');const update=()=>{const selected=[...app.querySelectorAll('input[name="rubric"]:checked')].map(x=>Number(x.value));const missing=[...rubrics].filter(x=>!selected.includes(Number(x.value))).map(x=>Number(x.value)+1);const status=document.getElementById('rubric-status');if(status)status.textContent=missing.length?'待核对/待完善：第 '+missing.join('、')+' 项':'全部要点已自行确认，仍不等于可靠自动评分';};rubrics.forEach(x=>{x.checked=checks.includes(Number(x.value));x.onchange=()=>{reflection.oninput();update();};});update();}const el=document.getElementById('answer');if(el){el.value=session.draft||'';el.oninput=()=>save(el.value);}let selected=[];try{selected=JSON.parse(session.draft||'[]');}catch{}if(!Array.isArray(selected))selected=[];app.querySelectorAll('input[name="pick"]').forEach(p=>{p.checked=selected.includes(Number(p.value));p.onchange=()=>save(JSON.stringify([...app.querySelectorAll('input[name="pick"]:checked')].map(x=>Number(x.value))));});}

function render(){const u=pack.units.find(x=>x.id===session.unitId);const stages={learn:'学习',recall:'闭卷',practice:'练题',feedback:'反馈',scheduled:'复习'};let html='<header class="learning-header"><button class="btn" id="back">返回任务</button><p class="stage-path">学习 → 闭卷 → 练题 → 反馈 → 复习</p><p class="current-stage">现在：'+stages[session.stage]+'</p></header><h1>'+esc(u.title)+'</h1>';
if(session.stage==='learn')html+='<section class="card"><h2>先理解</h2><p>'+esc(u.explanation)+'</p><h2>定义</h2><p>'+esc(u.definition)+'</p><h2>条件与边界</h2><p>'+esc(u.conditions)+'</p><h2>例子</h2><p>'+esc(u.example)+'</p><h2>误区</h2>'+u.misconceptions.map(x=>'<p>'+esc(x)+'</p>').join('')+'<button class="btn block" id="learned">隐藏讲解，开始闭卷</button></section>';
else if(session.stage==='recall')html+='<section class="card"><h2>不看答案独立回忆</h2>'+(session.mode==='review'?[u.review.delayedPrompt||'重新独立回忆关键概念']:u.recall).map(x=>'<p>'+esc(x)+'</p>').join('')+'<label>我的闭卷回答<textarea id="answer"></textarea></label><button class="btn block" id="recall">保存回答，开始练题</button></section>';
else if(session.stage==='practice'){const q=controller.questions(session)[session.index];html+='<section class="card"><p>第'+(session.index+1)+'题 / '+controller.questions(session).length+'</p><h2>'+esc(q.stem)+'</h2>';if(q.type==='single'||q.type==='multi')html+='<fieldset><legend>独立选择答案</legend>'+q.options.map((x,i)=>'<label class="choice"><input name="pick" type="'+(q.type==='multi'?'checkbox':'radio')+'" value="'+i+'"> '+esc(x)+'</label>').join('')+'</fieldset>';else html+='<label>我的答案'+(q.type==='number'?'（单位 '+esc(q.unit)+'）':'')+'<textarea id="answer"></textarea></label>';html+='<button class="btn block" id="submit">提交并保存</button></section>';}
else if(session.stage==='feedback'){const f=session.feedback;html+='<section class="card"><h2>'+esc(f.grade.correct===null?'已保存，主观题需按要点核对':f.grade.correct?'答对':'答错，已保存错题')+'</h2>'+answerCard(f)+rubricCard(f.questionSnapshot)+'<label>我的错因或待完善点<select id="cause"><option value="unclassified">尚未判断</option><option value="concept">概念没理解</option><option value="calculation">计算错误</option><option value="reading">审题错误</option><option value="memory">没有记住</option><option value="incomplete">回答不完整</option></select><textarea id="reflection" placeholder="记录哪里没掌握；主观题按评分要点自行核对"></textarea></label><button class="btn block" id="next">继续 / 安排复习</button></section>';}
else html+='<section class="card"><h2>本轮已保存</h2><p>系统已安排延迟复习。完成不等于掌握，主观题暂不自动计分。</p><button class="btn block" id="review">到期后开始复习</button></section>';
app.innerHTML=html;if(typeof window.scrollTo==='function')window.scrollTo({top:0,behavior:'instant'});bind('back',overview);wireDraft();bind('learned',async()=>{session=await controller.learned(session);render();});bind('recall',async()=>{session=await controller.recall(session,document.getElementById('answer').value);render();});bind('submit',async()=>{const q=controller.questions(session)[session.index];let value;if(q.type==='single'||q.type==='multi'){const picks=[...app.querySelectorAll('input[name="pick"]:checked')].map(x=>Number(x.value));if(!picks.length)throw Error('请选择答案');value=q.type==='single'?picks[0]:picks;}else{const text=document.getElementById('answer').value.trim();if(!text)throw Error('请填写答案');if(q.type==='number'&&!Number.isFinite(Number(text)))throw Error('请填写数字');value=q.type==='number'?{value:Number(text),unit:q.unit}:text;}session=await controller.answer(session,value);render();});bind('next',async()=>{session=await controller.next(session,{cause:document.getElementById('cause')?.value,note:document.getElementById('reflection')?.value,selfRubric:[...app.querySelectorAll('input[name="rubric"]:checked')].map(x=>Number(x.value))});render();});bind('review',async()=>{session=await controller.review(session);render();});}
(async()=>{try{const r=await fetch('representative-courses.json');if(!r.ok)throw Error('课程加载失败');pack=await r.json();const errors=CourseEngine.validate(pack);if(errors.length)throw Error('课程包检查失败：'+errors.join(','));if(pack.units.some(u=>u.reviewStatus!=='internally-reviewed-for-pilot'||!u.reviewRecord))throw Error('样板内容未完成内部核查，暂停加载');await home();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>{message.textContent='可在线学习；离线准备失败：'+e.message;});}catch(e){error(e);}})();
